name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
 BAR_CREATION: /opt/ace-11.0.0.7/tools/mqsicreatebar
 BAR_STORE: /home/bandaru/Templates
 DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
 OPENSHIFT_USERNAME: ${{ secrets.OPENSHIFT_USERNAME }}
 OPENSHIFT_PASSWORD: ${{ secrets.OPENSHIFT_PASSWORD }}
 OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
 OPENSHIFT_SERVER_URL: ${{ secrets.OPENSHIFT_SERVER_URL }}
 
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Bar File Creation
        run: $BAR_CREATION -data /root -b $BAR_STORE/Rest_Api_Application_Put_Get.bar -a Rest_Api_Application_Put_Get
            
      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
         openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
         openshift_username: ${{ env.OPENSHIFT_USERNAME }}
         openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}
         insecure_skip_tls_verify: true
         namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      
                  
      
      
      
        
          
          
       
      

