-  name: Configure AWS credentials
   uses: aws-actions/configure-aws-credentials@v1
   with:
     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     aws-region: <<YOUR_S3_REGION>>
-  name: Deploy static files to AWS S3
   id: aws-deploy-s3
   uses: oneyedev/aws-deploy-s3@v2
   with:
     region: <<ap-south-1>
     bucket: <<manojeidiko>>
     source: <</home/bandaru/Pictures>>
     target: <<manojeidiko>>
